spring:
  main:
    banner-mode: off

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
app:
  description: Dev version of credit service
  version: 0.0.1-SNAPSHOT
  server:
    stage: dev